In [6]:
import numpy as np
import cv2

bg = cv2.imread('background.png', 1)
bg = cv2.resize(bg, (640, 480))

img = cv2.imread('StillImage.png', 1)
img = cv2.resize(img, (640, 480))

cv2.imshow('bg', bg)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# compute the differences    
difference = cv2.absdiff(bg, img)
print(difference.shape)

# ???
difference = np.sum(difference, axis=2) / 3.0 # shape(H, W)
difference = difference.astype('uint8')
print(difference.shape)

cv2.imshow('difference', difference)
cv2.imwrite('difference.png', difference)
cv2.waitKey(0)
cv2.destroyAllWindows()

(480, 640, 3)
(480, 640)


In [13]:
# compute binary mask
import numpy as np
import cv2

difference = cv2.imread('difference.png', 1)
difference = cv2.resize(difference, (640, 480))

_, difference_binary = cv2.threshold(difference, 15, 255, cv2.THRESH_BINARY)
print(difference_binary.shape)

(480, 640, 3)


In [14]:
cv2.imshow('difference', difference)
cv2.imshow('difference_binary', difference_binary)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
# replace background

new_bg = cv2.imread('FakeBackground.png')
new_bg = cv2.resize(new_bg, (640, 480))

output = np.where(difference_binary==255, img, new_bg)
cv2.imshow("output", output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)

# get background
_, init_frame = cap.read()
init_frame = cv2.resize(init_frame, (640, 480))
cv2.imshow('Window-Title', init_frame)
cv2.imwrite('background2.png', init_frame)

cv2.waitKey(0)
cv2.destroyAllWindows()
cap.release()

In [ ]:
import numpy as np
import cv2


bg = cv2.imread('background.png', 1)
bg = cv2.resize(bg, (640, 480))

img = cv2.imread('StillImage.png', 1)
img = cv2.resize(img, (640, 480))

#bg  = cv2.GaussianBlur(bg, (5, 5), 0)
#img = cv2.GaussianBlur(img, (5, 5), 0)
    
difference = cv2.absdiff(bg, img)
print(type(difference[0][0][0]))
print(difference.shape)

difference = np.sum(difference, axis=2) / 3.0
difference = difference.astype('uint8')

print(type(difference[0][0]))
print(difference.shape)

cv2.imshow('bg', bg)
cv2.imshow('img', img)
cv2.imshow('difference', difference)

cv2.imwrite('difference.png', difference)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2


difference = cv2.imread('difference.png', 1)
difference = cv2.resize(difference, (640, 480))

_, difference_binary = cv2.threshold(difference, 15, 255, cv2.THRESH_BINARY)

cv2.imshow('difference', difference)
cv2.imshow('difference_binary', difference_binary)

cv2.imwrite('difference_binary.png', difference_binary)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2


bg = cv2.imread('background.png')
bg = cv2.resize(bg, (640, 480))

cap = cv2.VideoCapture(0)

# get background
_, init_frame = cap.read()
cv2.imshow('Window-Title', init_frame)
cv2.waitKey(0)

_, first_frame = cap.read()
first_frame = cv2.GaussianBlur(first_frame, (5, 5), 0)
cv2.imshow('Window-Title', first_frame)
cv2.waitKey(0)

# get live video
while(True):
    # Capture frame-by-frame
    _, frame = cap.read()
    frame = cv2.GaussianBlur(frame, (5, 5), 0)
    
    difference = cv2.absdiff(first_frame, frame)
    difference = np.sum(difference, axis=2) / 3.0
    _, difference = cv2.threshold(difference, 25, 255, cv2.THRESH_BINARY)
    
    diff3 = np.stack([difference, difference, difference], axis=2)
    output = np.where(diff3==0, bg, frame)
    
    cv2.imshow("First frame", first_frame)
    cv2.imshow("Frame", frame)
    cv2.imshow("difference", difference)
    cv2.imshow("output", output)

    key = cv2.waitKey(30)
    if key == 27:
        break

cv2.waitKey(0)
cv2.destroyAllWindows()
cap.release()

In [4]:
import numpy as np
import cv2

data = np.array([[0, 63, 174], 
                 [30, 205, 132], 
                 [52, 178, 210]])
data = data.astype(np.uint8)
print(data)

_, output = cv2.threshold(data, 100, 255, 
                          cv2.THRESH_BINARY)
print(output)

[[  0  63 174]
 [ 30 205 132]
 [ 52 178 210]]
[[  0   0 255]
 [  0 255 255]
 [  0 255 255]]


In [5]:
M = (output == 255)
print(M)

[[False False  True]
 [False  True  True]
 [False  True  True]]


In [9]:
data = np.array([[0, 1, 2], 
                 [2, 1, 2], 
                 [1, 2, 3]])
print(data.shape)

output = np.sum(data)
print(output)

(3, 3)
14


In [11]:
output = np.sum(data, axis=0)
print(output)

[3 4 7]
